# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Jumps to the right place
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  test:
    name: Maps the right tested files
    runs-on: self-hosted
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run tests
        run: nix develop -c make test
